wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690342491.699727
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 23
      4: 3.10.6
      5: 0.15.4
      6: 4.29.2
      8:
      - 1
      - 5
